stages:
  - prepare
  - compile
  - publish

build_image_compile:
  stage: prepare
  image: docker:git
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - git clone https://github.com/krallin/tini.git upstream --depth 1 -b master
    - docker build -t registry.gitlab.com/gbraad/tini:compile ./upstream
    - docker push registry.gitlab.com/gbraad/tini:compile

build_image_publish:
  stage: prepare
  image: docker:git
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/gbraad/tini:publish ./publish
    - docker push registry.gitlab.com/gbraad/tini:publish

build_tini:
  stage: compile
  image: registry.gitlab.com/gbraad/tini:compile
  script:
    - mkdir -p public
    - git clone https://github.com/krallin/tini.git upstream --depth 1 -b master
    - cd upstream
    - cmake .
    - make
    - make package
    - mv tini ../public
    - mv tini-static ../public
    - mv *.deb ../public
    - mv *.rpm ../public
  artifacts:
    paths:
      - public

pages:
  stage: publish
  image: registry.gitlab.com/gbraad/tini:publish
  script:
    - createrepo --database ./public
    - dpkg-scanpackages public | gzip -9c > public/Packages.gz
    - mv tini.repo ./public
    - ls ./public/ | ./genindex.sh > ./index.html
    - mv ./index.html ./public
  artifacts:
    paths:
       - public
